name: Merge Feature Branch

on:
  workflow_dispatch:
    inputs:
      feature_branch:
        description: 'Feature branch to merge'
        required: true
        type: choice
        options:
          - main
          - test1
          - test2
          # Add more branches as needed
      target_branch:
        description: 'Target branch to merge into'
        required: true
        default: 'qa1'
        type: choice
        options:
          - qa1
          - qa2
          - qa3

jobs:
  merge_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch Branches
        run: |
          BRANCHES=$(git ls-remote --heads origin | awk '{print $2}' | sed 's|refs/heads/||')
          echo "Available branches to merge:"
          echo $BRANCHES

      - name: Checkout Feature Branch
        uses: actions/checkout@v2
        with:
          ref: '${{ github.event.inputs.feature_branch }}'

      - name: Force Push to Target Branch
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Actions"
          git push --force origin HEAD:${{ github.event.inputs.target_branch }}
