name: Trigger all Workflows

on:
  workflow_dispatch:

jobs:
  trigger-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Set Branch Variable
        id: set-branch
        run: echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Call Build Workflows
        uses: actions/github-script@v6
        with:
          script: |
            const github = require('@actions/github');
            const token = process.env.GITHUB_TOKEN;
            const octokit = github.getOctokit(token);
            const branch = process.env.BRANCH;
            const workflows = [
              'build_backend.yml',
              'build_client_admin.yml',
              'build_client_ecom.yml'
            ];

            async function triggerWorkflow(workflow) {
              try {
                await octokit.actions.createWorkflowDispatch({
                  owner: github.context.repo.owner,
                  repo: github.context.repo.repo,
                  workflow_id: workflow,
                  ref: branch
                });
                console.log(`Successfully triggered ${workflow}`);
              } catch (error) {
                console.error(`Failed to trigger ${workflow}: ${error.message}`);
                throw error; // Throw error to stop the workflow
              }
            }

            try {
              const promises = workflows.map(workflow => triggerWorkflow(workflow));
              await Promise.all(promises);
            } catch (error) {
              console.error('One or more workflows failed to trigger.');
              process.exit(1); // Exit with a failure code
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
